// flow-typed signature: a72a7361da94af8c79377431a81b6cf9
// flow-typed version: <<STUB>>/libp2p-crypto_v^0.10.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libp2p-crypto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libp2p-crypto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libp2p-crypto/benchmarks/ephemeral-keys' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/benchmarks/key-stretcher' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/benchmarks/rsa' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/dist/index' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/dist/index.min' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/aes/ciphers-browser' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/aes/ciphers' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/aes/index-browser' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/aes/index' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/hmac/index-browser' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/hmac/index' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/hmac/lengths' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/index' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/keys/ecdh-browser' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/keys/ecdh' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/keys/ed25519-class' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/keys/ed25519' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/keys/ephemeral-keys' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/keys/index' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/keys/key-stretcher' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/keys/keys.proto' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/keys/rsa-browser' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/keys/rsa-class' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/keys/rsa-utils' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/keys/rsa' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/nodeify' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/random-bytes' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/util' {
  declare module.exports: any;
}

declare module 'libp2p-crypto/src/webcrypto' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libp2p-crypto/benchmarks/ephemeral-keys.js' {
  declare module.exports: $Exports<'libp2p-crypto/benchmarks/ephemeral-keys'>;
}
declare module 'libp2p-crypto/benchmarks/key-stretcher.js' {
  declare module.exports: $Exports<'libp2p-crypto/benchmarks/key-stretcher'>;
}
declare module 'libp2p-crypto/benchmarks/rsa.js' {
  declare module.exports: $Exports<'libp2p-crypto/benchmarks/rsa'>;
}
declare module 'libp2p-crypto/dist/index.js' {
  declare module.exports: $Exports<'libp2p-crypto/dist/index'>;
}
declare module 'libp2p-crypto/dist/index.min.js' {
  declare module.exports: $Exports<'libp2p-crypto/dist/index.min'>;
}
declare module 'libp2p-crypto/src/aes/ciphers-browser.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/aes/ciphers-browser'>;
}
declare module 'libp2p-crypto/src/aes/ciphers.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/aes/ciphers'>;
}
declare module 'libp2p-crypto/src/aes/index-browser.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/aes/index-browser'>;
}
declare module 'libp2p-crypto/src/aes/index.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/aes/index'>;
}
declare module 'libp2p-crypto/src/hmac/index-browser.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/hmac/index-browser'>;
}
declare module 'libp2p-crypto/src/hmac/index.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/hmac/index'>;
}
declare module 'libp2p-crypto/src/hmac/lengths.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/hmac/lengths'>;
}
declare module 'libp2p-crypto/src/index.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/index'>;
}
declare module 'libp2p-crypto/src/keys/ecdh-browser.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/keys/ecdh-browser'>;
}
declare module 'libp2p-crypto/src/keys/ecdh.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/keys/ecdh'>;
}
declare module 'libp2p-crypto/src/keys/ed25519-class.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/keys/ed25519-class'>;
}
declare module 'libp2p-crypto/src/keys/ed25519.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/keys/ed25519'>;
}
declare module 'libp2p-crypto/src/keys/ephemeral-keys.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/keys/ephemeral-keys'>;
}
declare module 'libp2p-crypto/src/keys/index.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/keys/index'>;
}
declare module 'libp2p-crypto/src/keys/key-stretcher.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/keys/key-stretcher'>;
}
declare module 'libp2p-crypto/src/keys/keys.proto.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/keys/keys.proto'>;
}
declare module 'libp2p-crypto/src/keys/rsa-browser.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/keys/rsa-browser'>;
}
declare module 'libp2p-crypto/src/keys/rsa-class.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/keys/rsa-class'>;
}
declare module 'libp2p-crypto/src/keys/rsa-utils.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/keys/rsa-utils'>;
}
declare module 'libp2p-crypto/src/keys/rsa.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/keys/rsa'>;
}
declare module 'libp2p-crypto/src/nodeify.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/nodeify'>;
}
declare module 'libp2p-crypto/src/random-bytes.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/random-bytes'>;
}
declare module 'libp2p-crypto/src/util.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/util'>;
}
declare module 'libp2p-crypto/src/webcrypto.js' {
  declare module.exports: $Exports<'libp2p-crypto/src/webcrypto'>;
}
