// flow-typed signature: e15cfed2f28559ff08cabf13892dd0f3
// flow-typed version: <<STUB>>/pem-jwk_v^1.5.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pem-jwk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pem-jwk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pem-jwk/bin/pem-jwk' {
  declare module.exports: any;
}

declare module 'pem-jwk/factor' {
  declare module.exports: any;
}

declare module 'pem-jwk/test/factor' {
  declare module.exports: any;
}

declare module 'pem-jwk/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pem-jwk/bin/pem-jwk.js' {
  declare module.exports: $Exports<'pem-jwk/bin/pem-jwk'>;
}
declare module 'pem-jwk/factor.js' {
  declare module.exports: $Exports<'pem-jwk/factor'>;
}
declare module 'pem-jwk/index' {
  declare module.exports: $Exports<'pem-jwk'>;
}
declare module 'pem-jwk/index.js' {
  declare module.exports: $Exports<'pem-jwk'>;
}
declare module 'pem-jwk/test/factor.js' {
  declare module.exports: $Exports<'pem-jwk/test/factor'>;
}
declare module 'pem-jwk/test/test.js' {
  declare module.exports: $Exports<'pem-jwk/test/test'>;
}
